export type RuneReference = {
  id: number
  name: string
  image: string
  category: 'tree' | 'rune'
}

export const RUNES: RuneReference[] = [
  { id: 8000, name: 'Precision', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/7201_Precision.png', category: 'tree' },
  { id: 8005, name: 'Press the Attack', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Precision/PressTheAttack/PressTheAttack.png', category: 'rune' },
  { id: 8008, name: 'Lethal Tempo', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Precision/LethalTempo/LethalTempoTemp.png', category: 'rune' },
  { id: 8009, name: 'Presence of Mind', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Precision/PresenceOfMind/PresenceOfMind.png', category: 'rune' },
  { id: 8010, name: 'Conqueror', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Precision/Conqueror/Conqueror.png', category: 'rune' },
  { id: 8014, name: 'Coup de Grace', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Precision/CoupDeGrace/CoupDeGrace.png', category: 'rune' },
  { id: 8017, name: 'Cut Down', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Precision/CutDown/CutDown.png', category: 'rune' },
  { id: 8021, name: 'Fleet Footwork', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Precision/FleetFootwork/FleetFootwork.png', category: 'rune' },
  { id: 8100, name: 'Domination', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/7200_Domination.png', category: 'tree' },
  { id: 8105, name: 'Relentless Hunter', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Domination/RelentlessHunter/RelentlessHunter.png', category: 'rune' },
  { id: 8106, name: 'Ultimate Hunter', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Domination/UltimateHunter/UltimateHunter.png', category: 'rune' },
  { id: 8112, name: 'Electrocute', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Domination/Electrocute/Electrocute.png', category: 'rune' },
  { id: 8126, name: 'Cheap Shot', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Domination/CheapShot/CheapShot.png', category: 'rune' },
  { id: 8128, name: 'Dark Harvest', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Domination/DarkHarvest/DarkHarvest.png', category: 'rune' },
  { id: 8135, name: 'Treasure Hunter', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Domination/TreasureHunter/TreasureHunter.png', category: 'rune' },
  { id: 8137, name: 'Sixth Sense', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Domination/SixthSense/SixthSense.png', category: 'rune' },
  { id: 8139, name: 'Taste of Blood', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Domination/TasteOfBlood/GreenTerror_TasteOfBlood.png', category: 'rune' },
  { id: 8140, name: 'Grisly Mementos', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Domination/GrislyMementos/GrislyMementos.png', category: 'rune' },
  { id: 8141, name: 'Deep Ward', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Domination/DeepWard/DeepWard.png', category: 'rune' },
  { id: 8143, name: 'Sudden Impact', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Domination/SuddenImpact/SuddenImpact.png', category: 'rune' },
  { id: 8200, name: 'Sorcery', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/7202_Sorcery.png', category: 'tree' },
  { id: 8210, name: 'Transcendence', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Sorcery/Transcendence/Transcendence.png', category: 'rune' },
  { id: 8214, name: 'Summon Aery', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Sorcery/SummonAery/SummonAery.png', category: 'rune' },
  { id: 8224, name: 'Axiom Arcanist', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Sorcery/NullifyingOrb/Axiom_Arcanist.png', category: 'rune' },
  { id: 8226, name: 'Manaflow Band', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Sorcery/ManaflowBand/ManaflowBand.png', category: 'rune' },
  { id: 8229, name: 'Arcane Comet', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Sorcery/ArcaneComet/ArcaneComet.png', category: 'rune' },
  { id: 8230, name: 'Stormraider\'s Surge', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Sorcery/PhaseRush/StormraidersSurgeRuneIcon2.png', category: 'rune' },
  { id: 8232, name: 'Waterwalking', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Sorcery/Waterwalking/Waterwalking.png', category: 'rune' },
  { id: 8233, name: 'Absolute Focus', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Sorcery/AbsoluteFocus/AbsoluteFocus.png', category: 'rune' },
  { id: 8234, name: 'Celerity', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Sorcery/Celerity/CelerityTemp.png', category: 'rune' },
  { id: 8236, name: 'Gathering Storm', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Sorcery/GatheringStorm/GatheringStorm.png', category: 'rune' },
  { id: 8237, name: 'Scorch', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Sorcery/Scorch/Scorch.png', category: 'rune' },
  { id: 8242, name: 'Unflinching', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Sorcery/Unflinching/Unflinching.png', category: 'rune' },
  { id: 8275, name: 'Nimbus Cloak', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Sorcery/NimbusCloak/6361.png', category: 'rune' },
  { id: 8299, name: 'Last Stand', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Sorcery/LastStand/LastStand.png', category: 'rune' },
  { id: 8300, name: 'Inspiration', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/7203_Whimsy.png', category: 'tree' },
  { id: 8304, name: 'Magical Footwear', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Inspiration/MagicalFootwear/MagicalFootwear.png', category: 'rune' },
  { id: 8306, name: 'Hextech Flashtraption', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Inspiration/HextechFlashtraption/HextechFlashtraption.png', category: 'rune' },
  { id: 8313, name: 'Triple Tonic', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Inspiration/PerfectTiming/AlchemistCabinet.png', category: 'rune' },
  { id: 8316, name: 'Jack Of All Trades', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Inspiration/JackOfAllTrades/JackofAllTrades2.png', category: 'rune' },
  { id: 8321, name: 'Cash Back', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Inspiration/CashBack/CashBack2.png', category: 'rune' },
  { id: 8345, name: 'Biscuit Delivery', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Inspiration/BiscuitDelivery/BiscuitDelivery.png', category: 'rune' },
  { id: 8347, name: 'Cosmic Insight', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Inspiration/CosmicInsight/CosmicInsight.png', category: 'rune' },
  { id: 8351, name: 'Glacial Augment', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Inspiration/GlacialAugment/GlacialAugment.png', category: 'rune' },
  { id: 8352, name: 'Time Warp Tonic', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Inspiration/TimeWarpTonic/TimeWarpTonic.png', category: 'rune' },
  { id: 8360, name: 'Unsealed Spellbook', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Inspiration/UnsealedSpellbook/UnsealedSpellbook.png', category: 'rune' },
  { id: 8369, name: 'First Strike', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Inspiration/FirstStrike/FirstStrike.png', category: 'rune' },
  { id: 8400, name: 'Resolve', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/7204_Resolve.png', category: 'tree' },
  { id: 8401, name: 'Shield Bash', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Resolve/MirrorShell/MirrorShell.png', category: 'rune' },
  { id: 8410, name: 'Approach Velocity', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Resolve/ApproachVelocity/ApproachVelocity.png', category: 'rune' },
  { id: 8429, name: 'Conditioning', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Resolve/Conditioning/Conditioning.png', category: 'rune' },
  { id: 8437, name: 'Grasp of the Undying', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Resolve/GraspOfTheUndying/GraspOfTheUndying.png', category: 'rune' },
  { id: 8439, name: 'Aftershock', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Resolve/VeteranAftershock/VeteranAftershock.png', category: 'rune' },
  { id: 8444, name: 'Second Wind', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Resolve/SecondWind/SecondWind.png', category: 'rune' },
  { id: 8446, name: 'Demolish', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Resolve/Demolish/Demolish.png', category: 'rune' },
  { id: 8451, name: 'Overgrowth', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Resolve/Overgrowth/Overgrowth.png', category: 'rune' },
  { id: 8453, name: 'Revitalize', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Resolve/Revitalize/Revitalize.png', category: 'rune' },
  { id: 8463, name: 'Font of Life', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Resolve/FontOfLife/FontOfLife.png', category: 'rune' },
  { id: 8465, name: 'Guardian', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Resolve/Guardian/Guardian.png', category: 'rune' },
  { id: 8473, name: 'Bone Plating', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Resolve/BonePlating/BonePlating.png', category: 'rune' },
  { id: 8992, name: 'Deathfire Touch', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Sorcery/DeathfireTouch/DEATHFIRE_TOUCH_KEYSTONE.png', category: 'rune' },
  { id: 9101, name: 'Absorb Life', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Precision/AbsorbLife/AbsorbLife.png', category: 'rune' },
  { id: 9103, name: 'Legend: Bloodline', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Precision/LegendBloodline/LegendBloodline.png', category: 'rune' },
  { id: 9104, name: 'Legend: Alacrity', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Precision/LegendAlacrity/LegendAlacrity.png', category: 'rune' },
  { id: 9105, name: 'Legend: Haste', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Precision/LegendHaste/LegendHaste.png', category: 'rune' },
  { id: 9111, name: 'Triumph', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Precision/Triumph.png', category: 'rune' },
  { id: 9923, name: 'Hail of Blades', image: 'https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Domination/HailOfBlades/HailOfBlades.png', category: 'rune' },
]

export function getRuneById(runeId: number): RuneReference | undefined {
  return RUNES.find((rune) => rune.id === runeId)
}